Update append_temp_files.yml

diff --git a/.github/workflows/append_temp_files.yml b/.github/workflows/append_temp_files.yml
--- a/.github/workflows/append_temp_files.yml
+++ b/.github/workflows/append_temp_files.yml
@@ -4,9 +4,7 @@ on:
   push:
     branches:
       - main
-permissions:  
-  contents: write
-  
+
 jobs:
   append-temp-files:
     runs-on: ubuntu-latest
@@ -17,6 +15,8 @@ jobs:
 
     - name: Append temp files to main files
       run: |
+        set -e
+        trap 'echo "Error: Process completed with exit code 1"; exit 1' ERR
         for i in {1..8}; do
           temp_file="hall_effect_sensor_${i}_temp.txt"
           main_file="hall_effect_sensor_${i}.txt"
@@ -30,6 +30,8 @@ jobs:
 
     - name: Commit changes
       run: |
+        set -e
+        trap 'echo "Error: Process completed with exit code 1"; exit 1' ERR
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
         git add .
